context:
  listener:
    classes: com.dingpw.hornbook.ApplicationEventListener
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://localhost/hornbook?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true

swagger:
    enabled: true
    title: "xxx"
    version: "1.0.0"
    contact:
        name: "Pengwei Ding"
        email: "www.dingpengwei@foxmail.com"
    path-mapping: "/"
    docket:
        draw:
            description: "绘制"
            base-path: "/drawer/.*"

